Re-release due to an error during the npm release
```
Run git push origin HEAD:${REF_NAME} --follow-tags
To https://github.com/sue445/rb-wasm-vdom
 * [new tag]         v0.7.0 -> v0.7.0
 ! [rejected]        HEAD -> main (fetch first)
error: failed to push some refs to 'https://github.com/sue445/rb-wasm-vdom'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

https://github.com/sue445/rb-wasm-vdom/actions/runs/34487367379/job/102904993260